#! /bin/sh
#all programs exe
pgrep -x sxhkd > /dev/null || sxhkd &
picom --backend glx --experimental-backends --blur-method dual_kawase & 
devilspie &
#sh /home/root99/.config/i3/wallpaper.sh &
bgchd -dir /home/root99/Downloads/Wall -bcknd feh -intv 30s -rpl &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
sh /home/root99/.config/polybar/launch.sh &
xss-lock --transfer-sleep-lock -- i3lock-fancy -g &&  systemctl suspend &
xautolock -time 30  -locker "systemctl suspend" -detectsleep &
nm-applet &


bspc monitor -d ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' '

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Brave-browser-nightly desktop='^2'
bspc rule -a Org.gnome.Nautilus desktop='^3'
bspc rule -a Code desktop='^4'
bspc rule -a Pcmanfm desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
